# ─────────────────────────────────────────────────────────────────────────────
# HOVER COMPILER & RUNTIME — Release Makefile
#
# Releases ship the C++ runtime as SOURCE, not as a prebuilt library: the
# user's own Zig compiles it via `hover --setup` (see runtimebuild.go). That
# makes the toolchain that builds the runtime and the one that builds
# sim.cpp the same by construction, which is the only way to be sure their
# C++ ABIs agree.
#
# The practical consequence for this Makefile is that packaging a platform
# is just a `go build` — there is no C++ cross-compilation here at all, and
# so no target triples, no per-platform object dirs, and no vendored Zig.
# Adding a platform is one row in PLATFORMS plus its GOOS/GOARCH, which is
# why Linux, Windows and the BSDs are all shipped.
#
# Targets:
#   make <platform>     → Package a single platform, e.g. `make linux-aarch64`
#   make all            → Package every platform into releases/$(VERSION)/
#   make check-runtime  → Compile the C++ runtime locally with warnings on.
#                         Not needed to package; run it in CI so runtime
#                         breakage surfaces here rather than on a user's
#                         machine at `hover --setup` time.
#   make clean          → Remove build artifacts, staging dirs and releases/
#   make help           → List targets
#
# make all VERSION=v1.2.3   (VERSION defaults to v0.0.0-dev if unset)
# ─────────────────────────────────────────────────────────────────────────────

# ── CONFIGURATION VARIABLES ───────────────────────────────────────────────────

# Host Zig — used only by `make check-runtime`. Packaging does not need Zig.
ZIG ?= zig

# Zig version stamped into Windows binaries as the one to download when no
# local Zig is found (see zigfetch.go). Windows has no package-manager
# convention to lean on, so `hover --setup` fetches this version itself.
# Derived from the host Zig by default; ziglang.org only serves the CURRENT
# master snapshot, so if you track master keep your host Zig current, or
# override with a tagged release (`make all ZIG_VERSION=0.16.0`) for a pin
# that never goes stale.
ZIG_VERSION ?= $(shell $(ZIG) version)

VERSION ?= v0.0.0-dev

STANDARD_LIB := stdlib
RUNTIME_DIR  := runtime

# `hover build` writes its generated simulator to sim.cpp in the CURRENT
# directory (main.go), so compiling any example from the repo root leaves a
# C++ file sitting in the Go package dir — and Go refuses to build a package
# containing C++ sources without cgo ("C++ source files not allowed"). It is
# regenerated by the next compile, so every `go build` below clears it first,
# the same way the Windows icon.syso is cleared.
GEN_SRCS := sim.cpp

# ── ICON TOOLING ──────────────────────────────────────────────────────────────
# The disc logo (assets/logo-disc.svg) has the version baked in as text, so it
# is stamped with $(VERSION) at build time — see the icon rules below. Windows
# binaries get the result embedded as their .exe icon; every package also gets
# the versioned PNG next to the binary. ELF/Mach-O have no embedded-icon
# concept, so the PNG is all non-Windows platforms can carry.
#
# Packaging therefore needs rsvg-convert and ImageMagick on PATH, plus
# llvm-windres when building Windows targets.
RSVG_CONVERT ?= rsvg-convert
MAGICK       ?= magick
LLVM_WINDRES ?= llvm-windres

# ── PLATFORM MATRIX ────────────────────────────────────────────────────────────
# Only GOOS/GOARCH: the C++ side is built on the user's machine, natively.
#
# Because packaging is now just `go build`, a platform costs two lines here
# rather than a cross-compiled C++ toolchain — which is what makes the BSDs
# practical. A platform ships if it clears all THREE gates:
#
#   1. Go builds the CLI:  GOOS=<os> GOARCH=<arch> go build -o /dev/null .
#   2. Zig builds the runtime, since the user compiles it locally:
#      zig c++ -std=c++17 -Iruntime -Iruntime/Eigen -target <arch>-<os> \
#          -c runtime/mna/engine.cpp -o /tmp/t.o
#   3. The user can OBTAIN Zig there — i.e. ziglang.org's download index
#      lists an <arch>-<os> host build. Without it `hover --setup` has no
#      compiler to run and the package is inert.
#
# Gate 3 is the one that is easy to forget, and it is why three otherwise-
# viable Go/Zig targets are absent: freebsd/386, openbsd/386 and
# openbsd/ppc64 have no official Zig build (Zig ships powerpc64le-freebsd,
# which is a different platform). DragonFly and Solaris fail gate 2.

PLATFORMS := linux-x86_64 linux-aarch64 linux-x86 linux-riscv64 \
             windows-x86_64 windows-aarch64 windows-x86 \
             freebsd-x86_64 freebsd-aarch64 freebsd-arm \
             netbsd-x86_64 netbsd-aarch64 netbsd-arm netbsd-x86 \
             openbsd-x86_64 openbsd-aarch64 openbsd-arm openbsd-riscv64

linux-x86_64_GOOS      := linux
linux-x86_64_GOARCH    := amd64

linux-aarch64_GOOS     := linux
linux-aarch64_GOARCH   := arm64

linux-x86_GOOS         := linux
linux-x86_GOARCH       := 386

linux-riscv64_GOOS     := linux
linux-riscv64_GOARCH   := riscv64

windows-x86_64_GOOS    := windows
windows-x86_64_GOARCH  := amd64

windows-aarch64_GOOS   := windows
windows-aarch64_GOARCH := arm64

windows-x86_GOOS       := windows
windows-x86_GOARCH     := 386

# llvm-windres COFF targets for embedding the icon into Windows .exe files.
# Named after the Go arch because that is what the .syso must match — Go links
# any .syso in the package dir into whatever it builds, so a machine-type
# mismatch (or a stray file during a non-Windows build) breaks the link.
windows-x86_64_WINDRES  := x86_64-w64-windows-gnu
windows-aarch64_WINDRES := aarch64-w64-windows-gnu
windows-x86_WINDRES     := i686-w64-windows-gnu

freebsd-x86_64_GOOS    := freebsd
freebsd-x86_64_GOARCH  := amd64

freebsd-aarch64_GOOS   := freebsd
freebsd-aarch64_GOARCH := arm64

freebsd-arm_GOOS       := freebsd
freebsd-arm_GOARCH     := arm

netbsd-x86_64_GOOS     := netbsd
netbsd-x86_64_GOARCH   := amd64

netbsd-aarch64_GOOS    := netbsd
netbsd-aarch64_GOARCH  := arm64

netbsd-arm_GOOS        := netbsd
netbsd-arm_GOARCH      := arm

netbsd-x86_GOOS        := netbsd
netbsd-x86_GOARCH      := 386

openbsd-x86_64_GOOS    := openbsd
openbsd-x86_64_GOARCH  := amd64

openbsd-aarch64_GOOS   := openbsd
openbsd-aarch64_GOARCH := arm64

openbsd-arm_GOOS       := openbsd
openbsd-arm_GOARCH     := arm

openbsd-riscv64_GOOS   := openbsd
openbsd-riscv64_GOARCH := riscv64

# ── DEFAULT TARGETS ───────────────────────────────────────────────────────────

.PHONY: all clean help check-runtime $(PLATFORMS) linux windows

all: $(PLATFORMS)

# Back-compat aliases for the old two-platform names.
linux: linux-x86_64
windows: windows-x86_64

# ── ICON (versioned disc logo) ────────────────────────────────────────────────
# Stamps $(VERSION) into the disc logo SVG and rasterizes it. The version in
# the SVG is just placeholder text; the stamp replaces whatever string the
# version <text> element (anchored by its x="180" y="278" position) currently
# holds, so the artwork can be updated without touching this Makefile.
ICON_DIR  := build/icon
ICON_SVG  := assets/logo-disc.svg
ICON_VSVG := $(ICON_DIR)/logo-disc-versioned.svg
ICON_ICO  := $(ICON_DIR)/hover.ico
ICON_PNG  := $(ICON_DIR)/hover.png
ICON_RC   := $(ICON_DIR)/hover.rc
ICON_SYSO := icon.syso

$(ICON_VSVG): $(ICON_SVG) FORCE
	@mkdir -p $(ICON_DIR)
	sed -E 's/(<text x="180" y="278"[^>]*>)[^<]*/\1$(VERSION)/' $(ICON_SVG) > $@
	@grep -qF '>$(VERSION)<' $@ || { echo "  ! could not stamp VERSION into $(ICON_SVG)"; exit 1; }

$(ICON_ICO): $(ICON_VSVG) FORCE
	for s in 16 32 48 256; do \
		$(RSVG_CONVERT) -w $$s -h $$s $(ICON_VSVG) -o $(ICON_DIR)/icon-$$s.png || exit 1; \
	done
	$(MAGICK) $(ICON_DIR)/icon-16.png $(ICON_DIR)/icon-32.png \
		$(ICON_DIR)/icon-48.png $(ICON_DIR)/icon-256.png $@
	cp $(ICON_DIR)/icon-256.png $(ICON_PNG)
	@# llvm-windres resolves the icon path relative to this file, so the bare
	@# filename here is correct as long as hover.rc and hover.ico sit together.
	printf '1 ICON "hover.ico"\n' > $(ICON_RC)

.PHONY: icon
icon: $(ICON_ICO)
	@echo "[icon] $(ICON_ICO) + $(ICON_PNG) stamped with $(VERSION)"

.PHONY: FORCE
FORCE:

# ── PER-PLATFORM PACKAGE TEMPLATE ─────────────────────────────────────────────

define PLATFORM_TEMPLATE

EXE_EXT_$(1) := $$(if $$(filter windows,$$($(1)_GOOS)),.exe,)
DIR_$(1)     := releases/$$(VERSION)/hover_$$(subst -,_,$$(VERSION))_$$(subst -,_,$(1))

.PHONY: $(1)
$(1): $(ICON_ICO)
	@printf '\n[$(1)] Assembling Hover Standalone...\n'
	@rm -rf $$(DIR_$(1))
	@mkdir -p $$(DIR_$(1))
	# Go links EVERY .syso in the package dir regardless of GOOS, so a leftover
	# Windows icon resource would break a Linux link. Clear it up front and
	# again right after the Windows build below.
	@rm -f $(ICON_SYSO) $(GEN_SRCS)
	# NO stdlib here — it is published to the web and downloaded by
	# `hover --setup` (see stdlib-archives below, and hpm/stdlib.go). This is
	# what lets a stdlib fix reach users without a compiler release; the cost
	# is that a fresh install needs network access once.
	# Runtime ships complete, sources included — `hover --setup` compiles it.
	cp -r $(RUNTIME_DIR) $$(DIR_$(1))/runtime
	rm -rf $$(DIR_$(1))/runtime/build
	$$(if $$(filter windows,$$($(1)_GOOS)),\
	  $(LLVM_WINDRES) --target=$$($(1)_WINDRES) $(ICON_RC) -O coff -o $(ICON_SYSO))
	GOOS=$$($(1)_GOOS) GOARCH=$$($(1)_GOARCH) go build -ldflags "-X main.zigVersion=$$(ZIG_VERSION)" -o $$(DIR_$(1))/hover$$(EXE_EXT_$(1)) .
	@rm -f $(ICON_SYSO)
	# Versioned logo next to the binary — the icon itself is already inside
	# the .exe on Windows; on ELF/Mach-O this file is the icon.
	cp $(ICON_PNG) $$(DIR_$(1))/hover.png
	# Attribution for the bundled third-party code (Eigen, klauspost/compress,
	# and Zig in the Windows packages). BSD-3 and Apache-2.0 both require the
	# notice to accompany a BINARY redistribution, which a release zip is.
	cp LICENSE THIRD_PARTY_LICENSES.md $$(DIR_$(1))/
	# `hpm` is the same binary, dispatched on argv[0] (see invokedAsHPM in
	# main.go), so `hpm install foo` and `hover hpm install foo` are the same
	# words in the same order. Windows gets a batch shim instead: symlinks
	# there need either developer mode or elevation, and zip does not carry
	# them portably anyway.
	$$(if $$(filter windows,$$($(1)_GOOS)),\
	  printf '@echo off\r\n"%%~dp0hover.exe" hpm %%*\r\n' > $$(DIR_$(1))/hpm.bat,\
	  ln -sf hover $$(DIR_$(1))/hpm)
	cd releases/$$(VERSION) && zip -r --symlinks hover-$$(VERSION)-$(1).zip $$(notdir $$(DIR_$(1)))
	@echo "[$(1)] Release ready: releases/$$(VERSION)/hover-$$(VERSION)-$(1).zip"

endef

$(foreach p,$(PLATFORMS),$(eval $(call PLATFORM_TEMPLATE,$(p))))

# ── STANDARD LIBRARY PUBLISHING ───────────────────────────────────────────────
# The stdlib is not bundled in releases; it is ONE ordinary package served
# over HTTP and installed by `hover --setup`. This target builds the archive
# to upload and the index entry that points at it.
#
# STDLIB_VERSION is deliberately separate from VERSION. Releases are tagged
# v0.8.0 while packages are semver 0.8.0, and — more importantly — a stdlib
# patch can ship as 0.8.1 with no compiler release at all, which is the whole
# reason for publishing it this way. `hover --setup` asks for ^0.8.0 and takes
# the newest matching.
STDLIB_VERSION ?= $(patsubst v%,%,$(VERSION))
STDLIB_OUT     := releases/stdlib/$(STDLIB_VERSION)

# Where the archives will be reachable once uploaded. Baked into the
# generated index entries, so set it to match your hosting.
STDLIB_BASE_URL ?= https://hover-lang.org/packages/stdlib/$(STDLIB_VERSION)

.PHONY: stdlib-archives
stdlib-archives:
	@printf '\n[stdlib] Packaging $(STDLIB_VERSION) from $(STANDARD_LIB)/\n'
	@rm -rf $(STDLIB_OUT)
	@mkdir -p $(STDLIB_OUT)/packages
	@rm -f $(GEN_SRCS)
	@go build -o $(STDLIB_OUT)/.hover-tool . || exit 1
	@test -f $(STANDARD_LIB)/hover.toml || { echo "  ! $(STANDARD_LIB)/hover.toml missing"; exit 1; }
	@# One archive, wrapped in a single stdlib/ directory. hpm strips exactly
	@# one wrapper on extraction, so the cache ends up holding math/,
	@# semiconductors/ ... directly — which is what the expansion in
	@# hpm/stdlib.go binds as one package root each.
	@#
	@# --sort/--owner/--group/--mtime make the tarball reproducible: without
	@# them the same sources produce a different archive every run. The
	@# content hash is taken over the unpacked tree so it would not change
	@# either way, but a byte-identical archive is what lets anyone rebuild
	@# this and check it against what was published.
	@tar --sort=name --owner=0 --group=0 --numeric-owner \
	     --mtime='UTC 2020-01-01' \
	     -C $(dir $(STANDARD_LIB)) -czf $(STDLIB_OUT)/stdlib-$(STDLIB_VERSION).tar.gz $(notdir $(STANDARD_LIB))
	@h=$$($(STDLIB_OUT)/.hover-tool hpm hash $(STANDARD_LIB)) || exit 1; \
	 printf 'name = "stdlib"\ndescription = "The Hover standard library"\nrepository = "https://github.com/hover-lang/hover"\n\n[[version]]\nversion = "%s"\nurl = "%s/stdlib-%s.tar.gz"\nhash = "%s"\n' \
	   "$(STDLIB_VERSION)" "$(STDLIB_BASE_URL)" "$(STDLIB_VERSION)" "$$h" \
	   > $(STDLIB_OUT)/packages/stdlib.toml; \
	 echo "  stdlib $(STDLIB_VERSION)  $$h"
	@rm -f $(STDLIB_OUT)/.hover-tool
	@# Ready-to-publish index archive. Wrapped in one top-level directory,
	@# matching what a tag archive from a repository host produces — hpm
	@# strips exactly one wrapper, so an unwrapped packages/ at the root would
	@# be stripped instead and the index would look empty.
	@rm -rf $(STDLIB_OUT)/.stage && mkdir -p $(STDLIB_OUT)/.stage/hover-index
	@cp -r $(STDLIB_OUT)/packages $(STDLIB_OUT)/.stage/hover-index/packages
	@tar -C $(STDLIB_OUT)/.stage -czf $(STDLIB_OUT)/index.tar.gz hover-index
	@rm -rf $(STDLIB_OUT)/.stage
	@echo "[stdlib] Archives + index entries in $(STDLIB_OUT)/"
	@echo "[stdlib] Upload the .tar.gz files under $(STDLIB_BASE_URL)/"
	@echo "[stdlib] Merge packages/*.toml into the index repo, then republish index.tar.gz"

# ── RUNTIME VERIFICATION (CI) ─────────────────────────────────────────────────
# Mirrors what `hover --setup` does on a user's machine, but with warnings
# enabled: users see -w, maintainers should not.

CHECK_DIR  := $(RUNTIME_DIR)/build/check
CHECK_SRCS := $(shell find $(RUNTIME_DIR) -name '*.cpp' -not -path '$(RUNTIME_DIR)/build/*')
CHECK_OBJS := $(patsubst $(RUNTIME_DIR)/%.cpp,$(CHECK_DIR)/%.o,$(CHECK_SRCS))

$(CHECK_DIR)/%.o: $(RUNTIME_DIR)/%.cpp
	@mkdir -p $(dir $@)
	$(ZIG) c++ -std=c++17 -O3 -Wall -Wextra \
		-I$(RUNTIME_DIR) -I$(RUNTIME_DIR)/Eigen -MMD -MP -c $< -o $@

check-runtime: $(CHECK_OBJS)
	$(ZIG) ar rcs $(CHECK_DIR)/libhover_runtime.a $(CHECK_OBJS)
	@echo "[Check] Runtime compiles cleanly: $(CHECK_DIR)/libhover_runtime.a"

-include $(CHECK_OBJS:.o=.d)

# ── UTILITIES ─────────────────────────────────────────────────────────────────

clean:
	@echo "Cleaning build artifacts..."
	rm -rf $(RUNTIME_DIR)/build
	rm -rf build
	rm -f $(ICON_SYSO) $(GEN_SRCS)
	rm -rf releases
	rm -rf hover_linux hover_win
	rm -f hover-linux-x64.zip hover-windows-x64.zip

help:
	@echo "Hover Release Build System"
	@echo "  make <platform>    - Package one platform:"
	@echo "                       $(PLATFORMS)"
	@echo "  make all           - Package every platform into releases/\$$(VERSION)/"
	@echo "  make icon          - Stamp \$$VERSION into the logo and build hover.ico/png"
	@echo "  make stdlib-archives - Package the standard library for the web"
	@echo "                       (releases do NOT bundle it; --setup downloads it)"
	@echo "  make check-runtime - Compile the C++ runtime locally (CI check)"
	@echo "  make clean         - Remove build artifacts"
	@echo ""
	@echo "  VERSION=$(VERSION) (override with VERSION=v1.2.3)"
	@echo "  Releases ship runtime SOURCE; users run 'hover --setup' to build"
	@echo "  it with their own Zig. Packaging needs Go, rsvg-convert and"
	@echo "  ImageMagick (plus llvm-windres for Windows icons), not Zig."
