// ── AUTO-GENERATED BY HOVER COMPILER — DO NOT EDIT ──────────────────────────
#include "hover_runtime.h"
#include <math.h>
#include <cstdint>
#include <math.h>

// ── ALL SIGNALS & VARIABLES ─────────────────────────────────────────────────
// Every variable is file-scope so it is visible across phase functions.
// State vars keep value between timesteps; locals are overwritten each step.
static double main_signal_source_v_sig = 0;
static double main_Q1_v_b = 0;
static double main_Q1_v_e = 0;
static double main_Q1_v_c = 0;
static double main_Q1_vbe = 0;
static double main_Q1_vbc = 0;
static double main_Q1_i_be = 0;
static double main_Q1_i_bc = 0;
static double main_Q1_i_ce = 0;

// ── USER-DEFINED FUNCTIONS ───────────────────────────────────────────────────
static double pnjlim(VM *vm, double v_new, double v_old, double vt, double v_crit);
static double limexp(VM *vm, double x);

static double pnjlim(VM *vm, double v_new, double v_old, double vt, double v_crit) {
    double pnjlim_v_new = v_new;
    double pnjlim_v_old = v_old;
    double pnjlim_vt = vt;
    double pnjlim_v_crit = v_crit;
    double pnjlim_result = pnjlim_v_new;
    if (((((((pnjlim_v_new) > (pnjlim_v_crit) ? 1.0 : 0.0)) != 0.0 && (((pnjlim_v_new) > (0.0) ? 1.0 : 0.0)) != 0.0) ? 1.0 : 0.0)) != 0.0) {
        double pnjlim_dv = ((pnjlim_v_new) - (pnjlim_v_old));
        if (((((((pnjlim_dv) > (((2.0) * (pnjlim_vt))) ? 1.0 : 0.0)) != 0.0 || (((pnjlim_dv) < ((((-(2.0))) * (pnjlim_vt))) ? 1.0 : 0.0)) != 0.0) ? 1.0 : 0.0)) != 0.0) {
            if ((((pnjlim_v_old) > (0.0) ? 1.0 : 0.0)) != 0.0) {
                double pnjlim_arg = ((1.0) + (((pnjlim_vt) == 0.0 ? 0.0 : (pnjlim_dv) / (pnjlim_vt))));
                if ((((pnjlim_arg) > (0.0) ? 1.0 : 0.0)) != 0.0) {
                    pnjlim_result = ((pnjlim_v_old) + (((pnjlim_vt) * (log((double)(pnjlim_arg))))));
                } else {
                    pnjlim_result = pnjlim_v_crit;
                }
            } else {
                pnjlim_result = ((pnjlim_vt) * (log((double)(((pnjlim_vt) == 0.0 ? 0.0 : (pnjlim_v_new) / (pnjlim_vt))))));
            }
        }
    }
    return pnjlim_result;
    return 0; // fallthrough
}

static double limexp(VM *vm, double x) {
    double limexp_x = x;
    double limexp_threshold = 80.0;
    if ((((limexp_x) < (limexp_threshold) ? 1.0 : 0.0)) != 0.0) {
        return exp((double)(limexp_x));
    }
    double limexp_e_t = exp((double)(limexp_threshold));
    return ((limexp_e_t) * (((1.0) + (((limexp_x) - (limexp_threshold))))));
    return 0; // fallthrough
}

// ── PHASE_STRUCTURAL ─────────────────────────────────────────────────────────────────────
static void phase_structural(VM *vm) {
    (void)(vm);
}

// ── PHASE_DIGITAL ─────────────────────────────────────────────────────────────────────
static void phase_digital(VM *vm) {
    (void)(vm);
}

// ── PHASE_ANALOG ─────────────────────────────────────────────────────────────────────
static void phase_analog(VM *vm) {
    (void)(vm);
    // main.signal_source
    main_signal_source_v_sig = ((1.03) + (((0.02) * (sin((double)(((((((2.0) * (3.1415926535900001))) * (1000))) * (vm->time))))))));
    // main.Q1
    main_Q1_v_b = api_V(vm->api, "main.q1_base");
    // main.Q1
    main_Q1_v_e = api_V(vm->api, "main.q1_emitter");
    // main.Q1
    main_Q1_v_c = api_V(vm->api, "main.q1_collector");
    // main.Q1
    main_Q1_vbe = ((main_Q1_v_b) - (main_Q1_v_e));
    // main.Q1
    main_Q1_vbc = ((main_Q1_v_b) - (main_Q1_v_c));
    // main.Q1
    if ((((main_Q1_vbe) > (0.75) ? 1.0 : 0.0)) != 0.0) {
        main_Q1_vbe = 0.75;
    }
    // main.Q1
    if ((((main_Q1_vbc) > (0.75) ? 1.0 : 0.0)) != 0.0) {
        main_Q1_vbc = 0.75;
    }
    // main.Q1
    if ((((main_Q1_vbe) < ((-(5.0))) ? 1.0 : 0.0)) != 0.0) {
        main_Q1_vbe = (-(5.0));
    }
    // main.Q1
    if ((((main_Q1_vbc) < ((-(5.0))) ? 1.0 : 0.0)) != 0.0) {
        main_Q1_vbc = (-(5.0));
    }
    // main.Q1
    main_Q1_i_be = ((((150) == 0.0 ? 0.0 : (1e-14) / (150))) * (((exp((double)(((0.025999999999999999) == 0.0 ? 0.0 : (main_Q1_vbe) / (0.025999999999999999))))) - (1.0))));
    // main.Q1
    main_Q1_i_bc = ((((3) == 0.0 ? 0.0 : (1e-14) / (3))) * (((exp((double)(((0.025999999999999999) == 0.0 ? 0.0 : (main_Q1_vbc) / (0.025999999999999999))))) - (1.0))));
    // main.Q1
    main_Q1_i_ce = ((1e-14) * (((exp((double)(((0.025999999999999999) == 0.0 ? 0.0 : (main_Q1_vbe) / (0.025999999999999999))))) - (exp((double)(((0.025999999999999999) == 0.0 ? 0.0 : (main_Q1_vbc) / (0.025999999999999999))))))));
}

// ── PHASE B — STAMP DRIVEN SOURCES ──────────────────────────────────────────
static void phase_b(VM *vm) {
    api_set_voltage_source(vm->api, "main.signal_source.voltage_source_1", main_signal_source_v_sig);
    api_set_current_source(vm->api, "main.Q1.current_source_9", main_Q1_i_be);
    api_set_current_source(vm->api, "main.Q1.current_source_10", main_Q1_i_bc);
    api_set_current_source(vm->api, "main.Q1.current_source_11", main_Q1_i_ce);
}

// ── STATE SNAPSHOT — save 'state' variables into vm->values ─────────────────
// Used by vm_save_state (snapshot.cpp) so ZCD probes and rejected solver
// steps can actually be rolled back — see emitStateVarSnapshot in codegen.
static void save_state_vars(VM *vm) {
    (void)(vm);
}

// ── STATE SNAPSHOT — restore 'state' variables from vm->values ──────────────
static void restore_state_vars(VM *vm) {
    (void)(vm);
}

// ── NETLIST PASS 1: register nodes & branches ────────────────────────────────
static void register_netlist(System *sys) {
    sys->register_node("main.vcc");
    sys->register_branch("main.voltage_source_0");
    sys->register_node("main.v_in");
    sys->register_branch("main.signal_source.voltage_source_1");
    sys->register_node("main.vcc");
    sys->register_node("main.q1_base");
    sys->register_node("main.vcc");
    sys->register_node("main.q1_collector");
    sys->register_node("main.q1_base");
    sys->register_node("main.q1_emitter");
    sys->register_node("main.mid");
    sys->register_node("main.v_in");
    sys->register_node("main.q1_base");
    sys->register_node("main.q1_emitter");
    sys->register_node("main.mid");
    sys->register_node("main.q1_base");
    sys->register_node("main.q1_emitter");
    sys->register_node("main.q1_base");
    sys->register_node("main.q1_collector");
    sys->register_node("main.q1_collector");
    sys->register_node("main.q1_emitter");
    sys->register_node("main.q1_base");
    sys->register_node("main.q1_emitter");
    sys->register_node("main.q1_base");
    sys->register_node("main.q1_collector");
    sys->register_node("main.q1_collector");
    sys->register_node("main.q1_emitter");
}

// ── NETLIST PASS 2: stamp values ─────────────────────────────────────────────
static void stamp_netlist(System *sys) {
    { int br = sys->resolve_branch("main.voltage_source_0"); stamp_voltage_source(sys, sys->resolve_node("main.vcc"), -1, 20, br); }
    { int br = sys->resolve_branch("main.signal_source.voltage_source_1"); stamp_voltage_source(sys, sys->resolve_node("main.v_in"), -1, 0.0, br); }
    stamp_resistor(sys, sys->resolve_node("main.vcc"), sys->resolve_node("main.q1_base"), 110000);
    stamp_resistor(sys, sys->resolve_node("main.vcc"), sys->resolve_node("main.q1_collector"), 10000);
    stamp_resistor(sys, sys->resolve_node("main.q1_base"), -1, 10000);
    stamp_resistor(sys, sys->resolve_node("main.q1_emitter"), -1, 1000);
    stamp_capacitor(sys, sys->resolve_node("main.mid"), -1, 1.5999999999999999e-05);
    stamp_capacitor(sys, sys->resolve_node("main.v_in"), sys->resolve_node("main.q1_base"), 3.4000000000000003e-07);
    stamp_resistor(sys, sys->resolve_node("main.q1_emitter"), sys->resolve_node("main.mid"), 74);
    stamp_current_source(sys, sys->resolve_node("main.q1_base"), sys->resolve_node("main.q1_emitter"), 0.0, "main.Q1.current_source_9");
    stamp_current_source(sys, sys->resolve_node("main.q1_base"), sys->resolve_node("main.q1_collector"), 0.0, "main.Q1.current_source_10");
    stamp_current_source(sys, sys->resolve_node("main.q1_collector"), sys->resolve_node("main.q1_emitter"), 0.0, "main.Q1.current_source_11");
    stamp_capacitor(sys, sys->resolve_node("main.q1_base"), sys->resolve_node("main.q1_emitter"), 9.9999999999999994e-12);
    stamp_capacitor(sys, sys->resolve_node("main.q1_base"), sys->resolve_node("main.q1_collector"), 3.9999999999999999e-12);
    stamp_capacitor(sys, sys->resolve_node("main.q1_collector"), sys->resolve_node("main.q1_emitter"), 2e-12);
}

// ── PHASE LOG — copy C globals into vm->values for logger ────────────────────
static void phase_log(VM *vm) {
}

// ── MAIN ─────────────────────────────────────────────────────────────────────
int main(void) {
    // Build system — two-pass: register then stamp
    System sys;
    system_init_empty(&sys, 9.9999999999999995e-07);
    register_netlist(&sys);  // pass 1: register all nodes and branches
    system_finalize(&sys);   // resize Eigen matrices to exact count
    stamp_netlist(&sys);     // pass 2: stamp values into correctly-sized matrices

    // Solver and API
    Solver solver;
    solver_init(&solver, &sys);
    API api;
    api_init(&api, &sys, &solver);

    // VM
    VM vm;
    vm.api        = &api;
    vm.solver     = &solver;
    vm.time       = 0.0;
    vm.time_step  = 9.9999999999999995e-07;
    vm.end_time   = 0.029999999999999999;
    vm.zcd_enabled = 0;
    vm.op_enabled  = 0;
    vm.jacobian_scratch = Eigen::MatrixXd::Zero(sys.size, sys.size);
    vm.base_b_scratch   = Eigen::VectorXd::Zero(sys.size);

    // Phase function pointers
    vm.phase_structural = phase_structural;
    vm.phase_digital    = phase_digital;
    vm.phase_analog     = phase_analog;
    vm.phase_b          = phase_b;
    vm.phase_log        = phase_log;
    vm.save_state_vars    = save_state_vars;
    vm.restore_state_vars = restore_state_vars;

    // Logger
    std::vector<std::string> mna_nodes = {"main.q1_base", "main.q1_collector"};
    std::vector<std::string> vm_signals = {};
    logger_init(&vm.logger, mna_nodes, vm_signals);

    // Solver strategy
    BDF2 strategy;
    strategy.max_dt = 9.9999999999999991e-06;
    vm.strategy = &strategy;

    vm_run(&vm);
    return 0;
}
