package hpm

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// LockVersion is the lockfile format version. Bumped only on a change that
// an older hover could not read correctly; an unknown version is refused
// rather than guessed at, since guessing means installing the wrong code.
const LockVersion = "1"

// LockedPackage is one fully resolved dependency: everything needed to
// reproduce the exact bytes, on any machine, without consulting an index.
//
// There is no commit field. An earlier draft recorded one alongside the
// hash, from when packages were fetched by cloning repositories. Once a
// package is an archive plus a content hash, the commit is redundant: a
// commit sha and a content hash are both immutable names for a tree, and the
// hash is the one that has to be computed anyway. Carrying both would be two
// answers to one question, with nothing deciding which wins if they ever
// disagreed.
type LockedPackage struct {
	Name    string // qualified, as written in the manifest
	Version string // resolved version, or "" for a URL/git dependency
	Index   string // originating index, or "" when not resolved through one
	URL     string // archive URL, or git remote when Git is set
	Git     bool   // fetched through the optional git transport
	Rev     string // git ref, only meaningful when Git is set
	Hash    string // "sha256:..." over the unpacked tree
}

// Lockfile is a parsed hover.lock.
type Lockfile struct {
	Path     string
	Packages []LockedPackage
}

// LoadLockfile reads dir/hover.lock. A missing file is not an error — a
// project that has never installed anything simply has no lock yet — so the
// caller gets an empty lockfile and a false.
func LoadLockfile(dir string) (*Lockfile, bool, error) {
	path := filepath.Join(dir, LockName)
	src, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return &Lockfile{Path: path}, false, nil
	}
	if err != nil {
		return nil, false, fmt.Errorf("could not read %s: %w", path, err)
	}

	doc, err := ParseTOML(string(src))
	if err != nil {
		return nil, false, fmt.Errorf("%s: %w", path, err)
	}

	lf := &Lockfile{Path: path}

	if root := doc.Table(); root != nil {
		if v, ok := root.Get("version"); ok && v != LockVersion {
			return nil, false, fmt.Errorf("%s: lockfile format version %s, but this hover understands version %s — delete it and re-run `hover hpm install` to regenerate",
				path, v, LockVersion)
		}
	}

	for _, t := range doc.Tables("package") {
		var p LockedPackage
		p.Name, _ = t.Get("name")
		p.Version, _ = t.Get("version")
		p.Index, _ = t.Get("index")
		p.URL, _ = t.Get("url")
		p.Rev, _ = t.Get("rev")
		p.Hash, _ = t.Get("hash")
		if g, ok := t.Get("git"); ok {
			p.Git = g == "true"
		}
		if p.Name == "" || p.Hash == "" {
			return nil, false, fmt.Errorf("%s: a [[package]] entry is missing `name` or `hash` — delete the lockfile and re-run `hover hpm install`", path)
		}
		lf.Packages = append(lf.Packages, p)
	}

	return lf, true, nil
}

// Get returns the locked entry for a qualified package name.
func (l *Lockfile) Get(name string) (LockedPackage, bool) {
	for _, p := range l.Packages {
		if p.Name == name {
			return p, true
		}
	}
	return LockedPackage{}, false
}

// Set inserts or replaces an entry.
func (l *Lockfile) Set(p LockedPackage) {
	for i := range l.Packages {
		if l.Packages[i].Name == p.Name {
			l.Packages[i] = p
			return
		}
	}
	l.Packages = append(l.Packages, p)
}

// Remove drops an entry by qualified name.
func (l *Lockfile) Remove(name string) bool {
	for i := range l.Packages {
		if l.Packages[i].Name == name {
			l.Packages = append(l.Packages[:i], l.Packages[i+1:]...)
			return true
		}
	}
	return false
}

// Save writes the lockfile. Unlike the manifest this is regenerated whole:
// it is a generated file, nobody hand-edits it, and a stable sort by name
// means two machines resolving the same dependencies produce byte-identical
// lockfiles — which is the only way `git diff hover.lock` stays readable.
func (l *Lockfile) Save() error {
	sorted := make([]LockedPackage, len(l.Packages))
	copy(sorted, l.Packages)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString("# Generated by `hover hpm`. Do not edit by hand.\n")
	b.WriteString("# Commit this file: it is what makes a build reproducible.\n")
	fmt.Fprintf(&b, "version = %q\n", LockVersion)

	for _, p := range sorted {
		b.WriteString("\n[[package]]\n")
		fmt.Fprintf(&b, "name = %q\n", p.Name)
		if p.Version != "" {
			fmt.Fprintf(&b, "version = %q\n", p.Version)
		}
		if p.Index != "" {
			fmt.Fprintf(&b, "index = %q\n", p.Index)
		}
		fmt.Fprintf(&b, "url = %q\n", p.URL)
		if p.Git {
			b.WriteString("git = true\n")
		}
		if p.Rev != "" {
			fmt.Fprintf(&b, "rev = %q\n", p.Rev)
		}
		fmt.Fprintf(&b, "hash = %q\n", p.Hash)
	}

	return writeFileAtomic(l.Path, []byte(b.String()))
}
