package codegen

import (
	"fmt"
	"strings"

	ast "hover/Interpreter/ast"
	"hover/Interpreter/elaborator"
)

// ─────────────────────────────────────────────────────────────────────────────
// PROGRAM HEADER
// ─────────────────────────────────────────────────────────────────────────────

func (g *generator) emitHeader() {
	g.raw(`// ── AUTO-GENERATED BY HOVER COMPILER — DO NOT EDIT ──────────────────────────`)
	g.raw(`#include "hover_runtime.h"`)
	g.raw(`#include <math.h>`)
	g.raw(`#include <cstdint>`)
	g.raw(``)
}

// ─────────────────────────────────────────────────────────────────────────────
// GLOBAL STATE VARIABLES
// ─────────────────────────────────────────────────────────────────────────────

// emitStateVars declares every variable collected by collectAllVars as a
// file-scope static, with its real declared C++ type (CType) rather than
// a uniform double. State variables get their real Hover initial value
// (cast to their declared type, since ParseEngineering always returns a
// Go float64 regardless of the variable's Hover type); plain locals get
// a zero of their declared type since they're reassigned at the top of
// whichever phase function writes them on every step anyway.
func (g *generator) emitStateVars() {
	g.raw(`// ── ALL SIGNALS & VARIABLES ─────────────────────────────────────────────────`)
	g.raw(`// Every variable is file-scope so it is visible across phase functions.`)
	g.raw(`// State vars keep value between timesteps; locals are overwritten each step.`)

	stateInits := g.collectStateInits()
	for _, name := range g.collectAllVars() {
		ht := g.typeOf(name)
		if init, isState := stateInits[name]; isState {
			g.raw(fmt.Sprintf("static %s = %s; // state", ht.cVarDecl(name), formatInitializer(ht, init)))
		} else if ht.isArray() {
			g.raw(fmt.Sprintf("static %s = {}; // zero-init", ht.cVarDecl(name)))
		} else {
			g.raw(fmt.Sprintf("static %s = %s;", ht.cVarDecl(name), formatTypedLiteral(0.0, ht.elem)))
		}
	}
	g.raw(``)
}

// formatInitializer builds the constant initializer (right of '=') for a
// file-scope static. Arrays accept a brace list {a, b, ...} or a single scalar
// that fills every element (the `double[2] arr = 1e-6` feature). nil -> {}.
func formatInitializer(ht hoverType, init ast.Expression) string {
	if !ht.isArray() {
		if num, ok := init.(*ast.NumberExpression); ok {
			return formatTypedLiteral(elaborator.ParseEngineering(num.Value), ht.elem)
		}
		return formatTypedLiteral(0.0, ht.elem)
	}
	return formatArrayLiteral(ht.elem, ht.dims, init)
}

// formatArrayLiteral builds a (possibly nested) C++ brace initializer for an
// array of the given element type and dimensions. Handles nested brace lists
// ({{1,2},{2,3}}) and scalar-fill at any level (double[2][2] = 1e-6).
func formatArrayLiteral(elem CType, dims []int, init ast.Expression) string {
	if len(dims) == 0 {
		if num, ok := init.(*ast.NumberExpression); ok {
			return formatTypedLiteral(elaborator.ParseEngineering(num.Value), elem)
		}
		return formatTypedLiteral(0.0, elem)
	}
	switch v := init.(type) {
	case *ast.ArrayExpression:
		parts := make([]string, 0, len(v.Elements))
		for _, el := range v.Elements {
			parts = append(parts, formatArrayLiteral(elem, dims[1:], el))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	case *ast.NumberExpression: // scalar-fill at this dimension level
		parts := make([]string, dims[0])
		for i := range parts {
			parts[i] = formatArrayLiteral(elem, dims[1:], v)
		}
		return "{" + strings.Join(parts, ", ") + "}"
	}
	return "{}"
}

// formatTypedLiteral formats a float64 value as the correct C++ literal
// for the given CType — integer types get a plain integer literal,
// floating types keep full-precision formatting.
func formatTypedLiteral(val float64, ctype CType) string {
	switch ctype {
	case CInt:
		return fmt.Sprintf("%d", int64(val))
	case CUInt:
		if val < 0 {
			val = 0
		}
		return fmt.Sprintf("%d", uint64(val))
	default:
		return fmt.Sprintf("%.17g", val)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────────────────────

// emitMain parses the simulation directives (see directives.go), emits
// phase_log now that the .save() signal list is known, then writes main():
// builds the System (two-pass register/finalize/stamp — see netlist.go),
// wires up the Solver/API/VM, sets the phase function pointers, configures
// the logger, selects the solver strategy, and calls vm_run.
func (g *generator) emitMain() error {
	cfg, err := g.parseSimConfig()
	if err != nil {
		return err
	}

	strategyStruct, err := solverStructName(cfg.solverType)
	if err != nil {
		return err
	}

	g.emitPhaseLog(cfg.saveVMSignals)

	g.raw(`// ── MAIN ─────────────────────────────────────────────────────────────────────`)
	g.raw(`int main(void) {`)
	g.push()

	g.line("// Build system — two-pass: register then stamp")
	g.line("System sys;")
	g.line("system_init_empty(&sys, %s);", cfg.tStep)
	g.line("register_netlist(&sys);  // pass 1: register all nodes and branches")
	g.line("system_finalize(&sys);   // resize Eigen matrices to exact count")
	g.line("stamp_netlist(&sys);     // pass 2: stamp values into correctly-sized matrices")
	g.raw("")

	g.line("// Solver and API")
	g.line("Solver solver;")
	g.line("solver_init(&solver, &sys);")
	g.line("API api;")
	g.line("api_init(&api, &sys, &solver);")
	g.raw("")

	g.line("// VM")
	g.line("VM vm;")
	g.line("vm.api        = &api;")
	g.line("vm.solver     = &solver;")
	g.line("vm.time       = 0.0;")
	g.line("vm.time_step  = %s;", cfg.tStep)
	g.line("vm.end_time   = %s;", cfg.tEnd)
	g.line("vm.zcd_enabled = %d;", boolToInt(cfg.zcdEnabled))
	g.line("vm.op_enabled  = %d;", boolToInt(cfg.opEnabled))
	g.line("vm.jacobian_scratch = Eigen::MatrixXd::Zero(sys.size, sys.size);")
	g.line("vm.base_b_scratch   = Eigen::VectorXd::Zero(sys.size);")
	g.raw("")

	g.line("// Phase function pointers")
	g.line("vm.phase_structural = phase_structural;")
	g.line("vm.phase_digital    = phase_digital;")
	g.line("vm.phase_analog     = phase_analog;")
	g.line("vm.phase_b          = phase_b;")
	g.line("vm.phase_log        = phase_log;")
	g.line("vm.save_state_vars    = save_state_vars;")
	g.line("vm.restore_state_vars = restore_state_vars;")
	g.raw("")

	g.line("// Logger")
	g.line("std::vector<std::string> mna_nodes = {%s};", quotedList(cfg.saveMNANodes))
	g.line("std::vector<std::string> vm_signals = {%s};", quotedList(cfg.saveVMSignals))
	g.line("logger_init(&vm.logger, mna_nodes, vm_signals);")
	g.raw("")

	g.line("// Solver strategy")
	g.line("%s strategy;", strategyStruct)
	g.emitSolverTuningOverrides(strategyStruct, cfg)
	g.line("vm.strategy = &strategy;")
	g.raw("")

	g.line("vm_run(&vm);")
	g.line("return 0;")

	g.pop()
	g.raw("}")

	return nil
}
